name: build-release
run-name: Building new release...
on:
  release:
    types: [published]
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install -y libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev libopengl0 '^libxcb.*-dev' libegl1 libdbus-glib-1-2
            # libgl1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build standalone
        run: |
          python -m venv mca-venv
          source mca-venv/bin/activate
          pip install --upgrade pip
          pip install . pyinstaller
          pyinstaller mca-linux.spec

      - name: Check dist folder
        run: ls -la dist/mca

      - name: Zip folder
        run: zip -r mca.zip dist/mca

      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: MCA ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      - name: "Get upload_url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"  
        id: release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./mca.zip
          asset_name: mca-${{ github.event.release.name }}.zip
          asset_content_type: application/zip
          upload_url: ${{ steps.release.outputs.upload_url}}
