name: build-release-windows
run-name: Building new Windows release...
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build standalone
        run: |
          pip install --upgrade pip
          pip install . pyinstaller
          pyinstaller mca-windows.spec

      - name: Run InnoSetup
        run: |
            "%programfiles(x86)%\\Inno Setup 6\\iscc.exe" "mca.iss"
        shell: cmd

      - name: "Get upload_url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
        id: release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: mca-*-setup.exe
          asset_name: mca-${{ github.event.release.name }}.exe
          asset_content_type: application
          upload_url: ${{ steps.release.outputs.upload_url}}
